apiVersion: v1

kind: Pod

metadeta:
    name: my-scheduler
    namespace: kube-system

spec:
    containers:
        - command:
              - kube-scheduler
              - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
              - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
              - --bind-address=127.0.0.1
              - --kubeconfig=/etc/kubernetes/scheduler.conf
              - --leader-elect=true
              - --port=
              image: k8s.gcr.io/kube-scheduler:v1.19.0
