apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: myapp

spec:
  template:
    metadata:
      name: my-app
      labels:
        app: myapp
    spec:
      containers:
        - name: my-frontend-container
          image: httpd:2.4-alpine

  replicas: 3
  selector:
    matchLabels:
      app: myapp